ログイン機能、メモ新規作成、一覧表示機能の実装
takashi6/laravel_simple_memo pull request #1
Opened 2022-01-21 12:01 UTC by takashi6

ログイン機能
  -> app/Http/Controllers/Auth/
メモ新規作成
  -> resources/views/create.blade.php
一覧表示機能
  -> resources/views/layouts/app.blade.php

2022-01-22 02:16 UTC, oratake reviewed
ざっくりですがレビュー書きましたー
全体の話ですと余裕が出たらコミットを分割するとよさそうです。
ログイン、メモ新規など、コミットメッセージに併記していたものはそれぞれを分割できるとおもうので、その単位でコミットされていると良さそうです

2022-01-22 02:17 UTC, mocchann requested changes
レビューしてみました！
もし、bladeをレビューしてもらうなら、コードだけじゃなくてキャプチャなど、どんなviewになっているのか確認できるものもあった方がレビューしやすいですね！

2022-01-22 02:17 UTC, mocchann commented on routes/web.php
> +Route::get('/home', [HomeController::class, 'index'])->name('home');
今ログイン機能も実装しているので、ルートグループを使った方がルーティングがわかりやすくなります。
下記はドキュメントの抜粋です。

```
Route::middleware(['first', 'second'])->group(function () {
    Route::get('/', function () {
        // １番目と２番目のミドルウェアを使用
    });

    Route::get('/user/profile', function () {
        // １番目と２番目のミドルウェアを使用
    });
});
```

参考：[https://readouble.com/laravel/8.x/ja/routing.html](url)

2022-01-22 02:17 UTC, mocchann commented on routes/web.php
> +Route::get('/home', [HomeController::class, 'index'])->name('home');
もし、resourceコントローラを作っていればルーティングをまとめて書けるので冗長にならずに済みます。
今回はわからなかったので参考までに。
これひとつでCRUDのルーティング全部いけます
```
Route::resource('photos', PhotoController::class);
```

[https://readouble.com/laravel/8.x/ja/controllers.html](url)

2022-01-22 02:17 UTC, mocchann commented on app/Http/Controllers/HomeController.php
> +        return redirect(route('home'));
route()で指定しても良いですが
```
action('HomeController@index');
```
のようにどのメソッドに飛ばすかを記述してあげるとわかりやすくなります。
このあたりはお好みで。

2022-01-22 02:17 UTC, mocchann commented on resources/views/layouts/auth.blade.php
> +                                       onclick="event.preventDefault();
このあたりの改行も見にくいので、インデント揃えたりしたほうが良いです。

2022-01-22 02:26 UTC, Samemura commented
PHPわからないので、ブランチとプルリクについてちょっとだけ。
プルリクは、もう少し細かい単位の方がわかりやすくて、作業するのもレビューするのもいいと思います 😄 
今回のだと、ログイン機能で一つ、メモの一覧表示・作成で１つが良さそうです（メモの一覧表示と作成を分けるのもありです）

そのときは、ブランチ名も大まかでいいのでわかりやすいものにしておくと、管理しやすいですよー 🎉 
例： `feature/login`, `feature/memo-index`

2022-01-22 02:26 UTC, mocchann commented on app/Http/Controllers/HomeController.php
> +    public function store(Request $request)
code sniffer入れるとコーディング規約チェックできて良いですよね！
[https://www.ritolab.com/entry/188](url)

2022-01-22 05:29 UTC, takashi6 commented on app/Http/Controllers/HomeController.php
> +        // dd(\Auth::id());
学習のために書いたものを残したままになっておりました、修正完了しました！

2022-01-22 05:35 UTC, takashi6 commented on app/Http/Controllers/HomeController.php
>      public function index()
すみません、インデント落ちを見つけられませんでした。
public function index() この行がインデント落ちしているということでしょうか？

2022-01-22 05:39 UTC, takashi6 commented on app/Http/Controllers/HomeController.php
> +    public function store(Request $request)
改行修正しました！
PSRまだまだ読み切れていないので勉強します！
code sniffer などのツールもひと段落したら入れてみます！

2022-01-22 05:58 UTC, takashi6 commented on resources/views/layouts/auth.blade.php
> +    <!-- CSRF Token -->
その違いは初めて知りました！
ありがとうございます！

2022-01-22 06:06 UTC, takashi6 commented on resources/views/auth/login.blade.php
>  <div class="container">
理解力無くてすみません
@section('content')
    <div class="container">
このようにインデントを一つ下げ忘れということでしょうか？

2022-01-22 07:03 UTC, takashi6 commented on resources/views/auth/register.blade.php
分かりました、これから不要な行は入れないように気を付けます。

2022-01-22 11:49 UTC, oratake commented on app/Http/Controllers/HomeController.php
>      public function index()
んあーこれブラウザから確認したらインデント正しいですね、すみません🙇
Githubアプリの表示がおかしいっぽかったです
コード的に合ってましたのでなかったことにしてください！

2022-01-23 22:19 UTC, takashi6 commented on app/Http/Controllers/HomeController.php
>      public function index()
分かりました！
ありがとうございます！
レビューの見方慣れていきたいと思います！

2022-01-23 22:47 UTC, takashi6 commented on routes/web.php
> +Route::get('/home', [HomeController::class, 'index'])->name('home');
不勉強で申し訳ありません
middleware()を使用して、Route::get, Route::post を一つのgroup にまとめて middleware(第一引数 , 第二引数) をグループ内のgetメソッド、postメソッドに割り当てていくという認識で会っていますでしょうか？

php artisan make:controller PhotoController --resource
を使用し、PhotoController.php を作成すれば URIを指定するだけで今行っている機能を短時間で実装できるのですね！

今の動画教材を一度作り終えたら、これらの情報をもとにリファクタリングしてみます！

2022-01-23 22:57 UTC, takashi6 commented on resources/views/layouts/auth.blade.php
> +                                       onclick="event.preventDefault();
修正しました！

2022-01-23 22:58 UTC, takashi6 commented on app/Http/Controllers/HomeController.php
> +        return redirect(route('home'));
こちらのほうがコメントを書かずに直感でどこに飛ぶのかわかりやすいですね
前項同様にリファクタリングした際にこちらで動かしてみます！

2022-01-24 03:15 UTC, merged